import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import Index, String, Text, text
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base


class ImageTypeEnum(str):
    AVATAR = "avatar"
    MEAL = "meal"
    PROGRESS = "progress"
    TEMPORARY = "temporary"


class UploadedImage(Base):
    """
    Metadata for uploaded images.

    File is stored on disk (local storage) at UPLOAD_DIR/{user_id}/{image_type}/{filename}.
    This table only stores metadata and the relative storage key.

    Retention:
    - avatar:      expires_at = NULL → never auto-deleted
    - meal:        expires_at = created_at + 7 days
    - temporary:   expires_at = created_at + 1 day
    - progress:    expires_at = NULL → never auto-deleted
    """

    __tablename__ = "uploaded_images"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
    )

    # Classification
    image_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default=ImageTypeEnum.MEAL,
        server_default=ImageTypeEnum.MEAL,
    )

    # File metadata from client
    original_filename: Mapped[str] = mapped_column(String(255), nullable=False)

    # Generated by backend
    stored_filename: Mapped[str] = mapped_column(String(255), nullable=False)

    # Relative path within UPLOAD_DIR, e.g. "user_uuid/meal/image_uuid.jpg"
    storage_key: Mapped[str] = mapped_column(Text, nullable=False)

    # MIME type
    content_type: Mapped[str] = mapped_column(String(100), nullable=False)

    # Bytes
    file_size: Mapped[int] = mapped_column(nullable=False, default=0)

    # Optional dimensions
    width: Mapped[Optional[int]] = mapped_column(nullable=True)
    height: Mapped[Optional[int]] = mapped_column(nullable=True)

    # SHA256 checksum for deduplication/debugging
    checksum: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # Retention / TTL
    expires_at: Mapped[Optional[datetime]] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=True,
        index=True,
    )

    # Soft delete
    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=True,
        index=True,
    )

    # Audit
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("now()"),
        onupdate=text("now()"),
    )

    # Optional link to entity (e.g. meal_log, progress_log)
    linked_entity_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    linked_entity_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
    )

    __table_args__ = (
        Index("idx_uploaded_images_user_id", "user_id"),
        Index("idx_uploaded_images_user_type", "user_id", "image_type"),
        Index("idx_uploaded_images_expires_deleted", "expires_at", "deleted_at"),
        Index("idx_uploaded_images_linked", "linked_entity_type", "linked_entity_id"),
    )
