"""remove image features

Revision ID: 372559ce19c2
Revises: add_hydration_goal_ml
Create Date: 2026-05-24 12:33:01.930244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '372559ce19c2'
down_revision: Union[str, Sequence[str], None] = 'add_hydration_goal_ml'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_logs', 'image_url')
    op.drop_column('meal_logs', 'image_storage_path')
    op.drop_table('uploaded_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('image_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('linked_entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('linked_entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='uploaded_images_pkey')
    )
    op.add_column('meal_logs', sa.Column('image_storage_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('meal_logs', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
