"""
Output Guardrails — Out-of-band enforcement for LLM text output.

This module provides deterministic, rule-based post-processing that runs
AFTER the LLM generates text and BEFORE it reaches the user. It serves
as the final safety net when system prompts are ignored or bypassed.

Guardrails implemented:
  1. Medical disclaimer appender: ensures user-facing health text always
     contains the standard medical disclaimer.
  2. Mode B prohibited phrase filter: scans and replaces judgmental
     language in behavioral nutrition responses.

Usage:
    from app.agents.output_guardrails import append_medical_disclaimer, filter_prohibited_phrases

    user_text = llm_output["user_facing_text"]
    user_text = append_medical_disclaimer(user_text, context="nutrition")
    user_text = filter_prohibited_phrases(user_text)
"""

from __future__ import annotations

import re
from typing import Literal

# ── Medical Disclaimer Templates ──────────────────────────────────────────────────


def _disclaimer_nutrition() -> str:
    return (
        "\n\nLưu ý: Thông tin dinh dưỡng trên chỉ mang tính tham khảo, "
        "không thay thế được tư vấn từ bác sĩ hoặc chuyên gia dinh dưỡng. "
        "Nếu bạn có tình trạng sức khỏe đặc biệt, hãy hỏi ý kiến bác sĩ trước khi thay đổi chế độ ăn."
    )


def _disclaimer_fitness() -> str:
    return (
        "\n\nLưu ý: Các bài tập trên chỉ mang tính tham khảo. "
        "Nếu bạn đang có chấn thương, đau nhức hoặc bệnh lý, hãy tham khảo ý kiến bác sĩ "
        "hoặc huấn luyện viên chuyên nghiệp trước khi tập luyện."
    )


def _disclaimer_health() -> str:
    return (
        "\n\nLưu ý: Mình không phải bác sĩ. "
        "Thông tin trên chỉ mang tính tham khảo và không thay thế được tư vấn y khoa chuyên môn. "
        "Nếu bạn có triệu chứng nghiêm trọng hoặc kéo dài, hãy gặp bác sĩ ngay."
    )


def _disclaimer_general() -> str:
    return (
        "\n\nLưu ý: Thông tin trên chỉ mang tính tham khảo, "
        "không thay thế được tư vấn y khoa hoặc dinh dưỡng chuyên nghiệp."
    )


_CONTEXT_DISCLAIMERS: dict[str, str] = {
    "nutrition": _disclaimer_nutrition,
    "fitness": _disclaimer_fitness,
    "health": _disclaimer_health,
}


# ── Prohibited Phrase Mappings (Mode B — behavioral nutrition) ───────────────────
# Maps judgmental / harmful phrases to empathetic alternatives.
# These are out-of-band enforced regardless of LLM behavior.
# "NEVER say" phrases from the system prompt are mechanically replaced here.

PROHIBITED_PHRASES: list[tuple[str, str]] = [
    # Judgmental about eating behavior
    ("đừng ăn",              "một lựa chọn nhẹ nhàng hơn có thể là..."),
    ("đừng bỏ bữa",         "thay vì bỏ bữa, bạn có thể thử..."),
    ("đừng ăn đêm",         "để giảm ăn đêm, thử uống nước ấm trước..."),
    ("bắt buộc phải",       "một gợi ý là..."),
    ("phải kiểm soát",      "bạn có thể thử..."),
    ("kiểm soát lại",       "bạn có thể nhận biết..."),
    ("không được ăn",        "một lựa chọn nhẹ nhàng hơn có thể là..."),
    ("cấm ăn",              "bạn có thể cân nhắc..."),
    ("bắt buộc phải nhịn",  "cơ thể cần năng lượng, nhưng bạn có thể..."),
    # Shame / blame language
    ("bạn sai",              ""),
    ("bạn có lỗi",          ""),
    ("đừng thèm",           "thèm ăn là phản ứng bình thường, bạn có thể..."),
    ("ngừng ăn",            ""),
    ("bạn nên ngừng",       "bạn có thể cân nhắc..."),
    ("tệ quá",               "đây là phản ứng bình thường, bạn có thể..."),
    ("kiêng ăn",             "thay vì kiêng hoàn toàn, bạn có thể..."),
    ("bắt buộc giảm cân",   "bạn có thể từ từ điều chỉnh..."),
]


# ── Disclaimer Appender ──────────────────────────────────────────────────────────


def append_medical_disclaimer(
    text: str,
    context: Literal["nutrition", "fitness", "health", "general"] = "general",
) -> str:
    """
    Append a medical disclaimer to user-facing text if one is not already present.

    Out-of-band enforcement: the disclaimer is mechanically added by Python code,
    not relying on the LLM to respect the system prompt.

    Args:
        text:     The user-facing text generated by the LLM
        context:  Domain context for choosing the right disclaimer template.
                  "nutrition" → nutrition-specific disclaimer
                  "fitness"   → fitness-specific disclaimer
                  "health"    → health monitoring disclaimer
                  "general"   → generic disclaimer

    Returns:
        The text with the appropriate medical disclaimer appended.
        If the text already contains a disclaimer (heuristic: "Lưu ý" anywhere in text),
        returns the original text unchanged.
    """
    if not text or not text.strip():
        return text

    # Scan the FULL text for disclaimer markers — prevents embedding a fake
    # disclaimer in the middle to bypass the check.
    full_text_lower = text.lower()
    if "lưu ý" in full_text_lower or "tham khảo" in full_text_lower or "không thay thế" in full_text_lower:
        return text

    # Select and append disclaimer
    if context in _CONTEXT_DISCLAIMERS:
        disclaimer = _CONTEXT_DISCLAIMERS[context]()
    else:
        disclaimer = _disclaimer_general()

    return text + disclaimer


# ── Prohibited Phrase Filter ─────────────────────────────────────────────────────


def filter_prohibited_phrases(text: str) -> str:
    """
    Scan and mechanically replace prohibited judgmental phrases in Mode B output.

    Out-of-band enforcement: even if the LLM ignores the "NEVER say" rules
    in the Mode B system prompt, these phrases are deterministically replaced.

    Args:
        text: User-facing text from Mode B behavioral nutrition response.

    Returns:
        The text with prohibited phrases replaced by empathetic alternatives.
        If no prohibited phrases are found, returns the original text unchanged.
    """
    if not text or not text.strip():
        return text

    original = text
    for prohibited, replacement in PROHIBITED_PHRASES:
        if prohibited.lower() in text.lower():
            # Case-insensitive replacement, preserve original case of surrounding text
            pattern = re.compile(re.escape(prohibited), re.IGNORECASE)
            text = pattern.sub(replacement, text)

    if text != original:
        # Append a gentle note that the response has been adjusted
        adjustment_note = (
            " Mình muốn đảm bảo rằng gợi ý này thấu hiểu và không gây áp lực. "
            "Nếu bạn cần hỗ trợ thêm, đừng ngần ngại hỏi nhé."
        )
        # Only add note if text ends with a sentence-like structure
        if text and text[-1] in ("。", ".", "!", "?"):
            text = text + adjustment_note

    return text


# ── Combined Guardrail ───────────────────────────────────────────────────────────


def apply_output_guardrails(
    text: str,
    context: Literal["nutrition", "fitness", "health", "general"] = "general",
    filter_mode_b: bool = False,
) -> str:
    """
    Apply all output guardrails in the correct order:
      1. Filter prohibited Mode B phrases (if requested)
      2. Append medical disclaimer

    Order matters: filter phrases first, then append disclaimer to the
    filtered text.

    Args:
        text:         The user-facing text from LLM output
        context:      Domain for disclaimer selection
        filter_mode_b: If True, apply Mode B prohibited phrase filter first

    Returns:
        Guardrail-processed user-facing text.
    """
    if not text:
        return text

    if filter_mode_b:
        text = filter_prohibited_phrases(text)

    text = append_medical_disclaimer(text, context=context)
    return text
