"""
Build CHAS v2 ablation comparison report from runner.py JSON outputs.
Reads summary fields directly (since runner emits tier_scores, not
per-metric breakdown) and synthesizes a Markdown comparison table.
"""
import json
import sys
from pathlib import Path
from typing import Any

CONFIGS = ["baseline", "partial", "full"]


def load_config(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def chas_from_runner(report: dict[str, Any]) -> dict[str, float]:
    """Compute CHAS-equivalent from summary fields emitted by runner.py."""
    summary = report.get("summary", {})
    pass_rate = float(summary.get("pass_rate", 0.0))
    overall_avg = float(summary.get("overall_score_avg", 0.0))
    total = int(summary.get("total", 0))
    failed = int(summary.get("failed", 0))
    duration = float(report.get("duration_seconds", 0.0))

    infra_breakdowns = int(summary.get("infra_breakdown", 0))
    pool_survival = 1.0 - (infra_breakdowns / total) if total else 1.0
    throughput_rps = (total / duration) if duration > 0 else 0.0

    # Performance_Score approximation: latency unknown → use duration-per-test
    avg_latency_ms = (duration * 1000.0) / total if total else 5000.0
    latency_score = max(0.0, min(1.0, 1.0 - (avg_latency_ms / 10000.0)))
    pool_score = pool_survival
    throughput_score = max(0.0, min(1.0, throughput_rps / 10.0))
    performance_score = round(
        0.45 * latency_score + 0.25 * pool_score + 0.20 * overall_avg
        + 0.10 * throughput_score,
        4,
    )

    # Quality_Score: derived from per-test tier_scores
    quality_vals: list[float] = []
    for r in report.get("results", []):
        ts = r.get("tier_scores", {}) or {}
        dq = ts.get("DOMAIN_QUALITY", 0.0) or 0.0
        quality_vals.append(dq)
    quality_score = round(sum(quality_vals) / len(quality_vals), 4) if quality_vals else 0.0

    # Safety_Score: derived from per-test tier_scores
    safety_vals: list[float] = []
    for r in report.get("results", []):
        ts = r.get("tier_scores", {}) or {}
        ns = ts.get("NUTRITION_SAFETY", 0.0) or 0.0
        safety_vals.append(ns)
    safety_score = round(sum(safety_vals) / len(safety_vals), 4) if safety_vals else 0.0

    chas = round(
        safety_score * 0.40
        + quality_score * 0.35
        + performance_score * 0.25,
        4,
    )
    return {
        "safety": safety_score,
        "quality": quality_score,
        "performance": performance_score,
        "chas": chas,
        "pass_rate": pass_rate,
        "overall_avg": overall_avg,
        "total": total,
        "failed": failed,
        "duration_s": duration,
        "avg_latency_ms": round(avg_latency_ms, 2),
    }


def render_md(reports: dict[str, dict[str, Any]], out: Path) -> None:
    rows = []
    rows.append("# SmartMeal Multi-Agent Ablation Report")
    rows.append("")
    rows.append("Generated by `scripts/build_chas_report.py` from runner.py JSON outputs.")
    rows.append("")
    rows.append("## CHAS v2 — Composite Health & Agent Score")
    rows.append("")
    rows.append("```")
    rows.append("CHAS v2 = (Safety_Score * 0.40)")
    rows.append("        + (Quality_Score * 0.35)")
    rows.append("        + (Performance_Score * 0.25)")
    rows.append("```")
    rows.append("")
    rows.append("| Config | Safety (0.40) | Quality (0.35) | Performance (0.25) | **CHAS** | Pass Rate | Total | Duration |")
    rows.append("|---|---|---|---|---|---|---|---|")
    for cfg in CONFIGS:
        r = reports.get(cfg)
        if r is None:
            rows.append(f"| {cfg} | _no data_ | - | - | - | - | - | - |")
            continue
        rows.append(
            f"| {cfg} | {r['safety']:.4f} | {r['quality']:.4f} | {r['performance']:.4f} "
            f"| **{r['chas']:.4f}** | {r['pass_rate']:.2%} | {r['total']} | {r['duration_s']:.1f}s |"
        )
    rows.append("")

    chas_values = {c: reports[c]["chas"] for c in CONFIGS if c in reports}
    if len(chas_values) >= 2:
        rows.append("## Δ CHAS (deltas)")
        rows.append("")
        rows.append("| Δ | Value |")
        rows.append("|---|---|")
        keys = list(chas_values.keys())
        for i, a in enumerate(keys):
            for b in keys[i + 1:]:
                d = round(chas_values[a] - chas_values[b], 4)
                rows.append(f"| CHAS({a}) − CHAS({b}) | {d:+.4f} |")
        winner = max(chas_values, key=chas_values.get)  # type: ignore[arg-type]
        rows.append("")
        rows.append(f"**Winner: `{winner}`** (CHAS = {chas_values[winner]:.4f})")
        rows.append("")

    rows.append("## Per-Test Tier Scores (full config)")
    rows.append("")
    full = reports.get("full", {})
    full_report_path = out.parent / "full_tier_a.json"
    if full_report_path.exists():
        with open(full_report_path, encoding="utf-8") as f:
            full_data = json.load(f)
        rows.append("| Test | Status | NUTRITION_SAFETY | DOMAIN_QUALITY | MULTI_AGENT_PERFORMANCE | Overall |")
        rows.append("|---|---|---|---|---|---|")
        for r in full_data.get("results", []):
            ts = r.get("tier_scores", {}) or {}
            rows.append(
                f"| {r.get('test_id', '?')} | {r.get('status', '?')} "
                f"| {ts.get('NUTRITION_SAFETY', 0):.4f} "
                f"| {ts.get('DOMAIN_QUALITY', 0):.4f} "
                f"| {ts.get('MULTI_AGENT_PERFORMANCE', 0):.4f} "
                f"| {r.get('overall_score', 0):.4f} |"
            )
    rows.append("")

    out.write_text("\n".join(rows), encoding="utf-8")


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    tier = sys.argv[1] if len(sys.argv) > 1 else "tier_a"
    files = {
        "baseline": here / f"baseline_{tier}.json",
        "partial": here / f"partial_{tier}.json",
        "full": here / f"full_{tier}.json",
    }
    out_md = here / f"chas_report_{tier}.md"

    print(f"Reading from: {here}")
    raw = {cfg: load_config(p) for cfg, p in files.items()}
    if all(r is None for r in raw.values()):
        print("ERROR: no input reports found")
        return 1

    chas = {cfg: chas_from_runner(r) for cfg, r in raw.items() if r is not None}
    render_md(chas, out_md)
    print(f"\n=== CHAS v2 ({tier}) ===")
    print(f"{'Config':<10} {'Safety':>8} {'Quality':>8} {'Perf':>8} {'CHAS':>8}  {'Pass':>6}")
    for cfg, r in chas.items():
        print(
            f"{cfg:<10} {r['safety']:>8.4f} {r['quality']:>8.4f} {r['performance']:>8.4f} "
            f"{r['chas']:>8.4f}  {r['pass_rate']:>6.1%}"
        )
    print(f"\nMarkdown report: {out_md}")
    return 0


if __name__ == "__main__":
    sys.exit(main())