"""
Build per-metric breakdown table from runner.py JSON outputs (after
runner.py was patched to embed metric_details).

Output: markdown table with the 7 individual metrics averaged per config.
"""
import json
import sys
from pathlib import Path
from collections import defaultdict


# Canonical ordering of the 7 metrics in the SMA-Eval v1 suite.
METRIC_ORDER = [
    ("AllergenViolationMetric",                "NUTRITION_SAFETY"),
    ("NutritionalConstraintViolationMetric",   "NUTRITION_SAFETY"),
    ("NutritionalEstimationErrorMetric",        "DOMAIN_QUALITY"),
    ("InterAgentConsistencyMetric",             "DOMAIN_QUALITY"),
    ("RecipeFeasibilityMetric",                 "DOMAIN_QUALITY"),
    ("AgentRoleAdherenceMetric",                "MULTI_AGENT_PERFORMANCE"),
    ("TaskDecompositionQualityMetric",          "MULTI_AGENT_PERFORMANCE"),
]


def load(path: Path) -> dict | None:
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def per_metric_avg(report: dict) -> dict[str, list[float]]:
    """Build dict[metric_name -> list of scores] across all tests in a report."""
    buckets: dict[str, list[float]] = defaultdict(list)
    for r in report.get("results", []):
        for md in r.get("metric_details", []) or []:
            name = md.get("name", "")
            if name == "UNKNOWN":
                continue
            score = md.get("score")
            if score is None:
                continue
            buckets[name].append(float(score))
    return buckets


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    tier = sys.argv[1] if len(sys.argv) > 1 else "tier_a"
    files = {
        "baseline": here / f"baseline_{tier}.json",
        "partial":  here / f"partial_{tier}.json",
        "full":     here / f"full_{tier}.json",
    }
    out_md = here / f"seven_metrics_{tier}.md"

    reports = {cfg: load(p) for cfg, p in files.items()}
    if all(r is None for r in reports.values()):
        print("ERROR: no input reports")
        return 1

    avgs: dict[str, dict[str, float]] = {}
    for cfg, r in reports.items():
        if r is None:
            continue
        buckets = per_metric_avg(r)
        avgs[cfg] = {
            name: round(sum(buckets[name]) / len(buckets[name]), 4)
            if buckets.get(name) else None
            for name, _ in METRIC_ORDER
        }

    rows: list[str] = []
    rows.append("# SMA-Eval v1 — 7-Metric Per-Config Breakdown")
    rows.append("")
    rows.append("Generated by `scripts/build_seven_metrics.py` from runner.py JSON outputs.")
    rows.append("")
    rows.append("| # | Metric | Group | Weight | baseline | partial | full |")
    rows.append("|---|---|---|---|---|---|---|")
    for idx, (name, group) in enumerate(METRIC_ORDER, start=1):
        weight = {
            "NUTRITION_SAFETY": 0.40 / 2,
            "DOMAIN_QUALITY":   0.35 / 3,
            "MULTI_AGENT_PERFORMANCE": 0.25 / 2,
        }[group]
        cells = []
        for cfg in ("baseline", "partial", "full"):
            v = avgs.get(cfg, {}).get(name)
            cells.append(f"{v:.4f}" if v is not None else "—")
        rows.append(
            f"| {idx} | `{name}` | {group} | {weight:.3f} "
            f"| {cells[0]} | {cells[1]} | {cells[2]} |"
        )
    rows.append("")

    # Group rollups for quick check
    rows.append("## Group rollups (average per group across all tests in config)")
    rows.append("")
    rows.append("| Group | baseline | partial | full |")
    rows.append("|---|---|---|---|")
    for group_name in ("NUTRITION_SAFETY", "DOMAIN_QUALITY", "MULTI_AGENT_PERFORMANCE"):
        cells = []
        for cfg in ("baseline", "partial", "full"):
            metric_names = [n for n, g in METRIC_ORDER if g == group_name]
            vals = [avgs.get(cfg, {}).get(n) for n in metric_names]
            vals = [v for v in vals if v is not None]
            avg = round(sum(vals) / len(vals), 4) if vals else None
            cells.append(f"{avg:.4f}" if avg is not None else "—")
        rows.append(f"| {group_name} | {cells[0]} | {cells[1]} | {cells[2]} |")
    rows.append("")

    # Pass-rate per metric per config (count(score >= 0.8) / total)
    rows.append("## Pass rate per metric (proportion of tests with score ≥ 0.8)")
    rows.append("")
    rows.append("| Metric | baseline | partial | full |")
    rows.append("|---|---|---|---|")
    pass_avgs: dict[str, dict[str, float]] = {}
    for cfg, r in reports.items():
        if r is None:
            continue
        buckets_all = per_metric_avg(r)
        # Re-do with passed count, not score avg
        passed: dict[str, list[bool]] = defaultdict(list)
        for rr in r.get("results", []):
            for md in rr.get("metric_details", []) or []:
                n = md.get("name", "")
                if n == "UNKNOWN":
                    continue
                if md.get("score") is None:
                    continue
                passed[n].append(bool(md.get("passed", False)))
        pass_avgs[cfg] = {
            n: round(sum(passed[n]) / len(passed[n]), 4) if passed.get(n) else 0.0
            for n, _ in METRIC_ORDER
        }

    for name, _ in METRIC_ORDER:
        cells = []
        for cfg in ("baseline", "partial", "full"):
            v = pass_avgs.get(cfg, {}).get(name)
            cells.append(f"{v:.2%}" if v is not None else "—")
        rows.append(f"| `{name}` | {cells[0]} | {cells[1]} | {cells[2]} |")
    rows.append("")

    # Full config per-test detail
    full = reports.get("full")
    if full:
        rows.append("## Per-test detail (full config)")
        rows.append("")
        rows.append("| Test | Status | Allergen | NCV | NEE | IAC | RFS | ARA | TDQ |")
        rows.append("|---|---|---|---|---|---|---|---|---|")
        metric_short = {
            "AllergenViolationMetric":               "Allergen",
            "NutritionalConstraintViolationMetric":  "NCV",
            "NutritionalEstimationErrorMetric":      "NEE",
            "InterAgentConsistencyMetric":           "IAC",
            "RecipeFeasibilityMetric":               "RFS",
            "AgentRoleAdherenceMetric":              "ARA",
            "TaskDecompositionQualityMetric":        "TDQ",
        }
        for r in full.get("results", []):
            score_by_name = {
                md.get("name"): md.get("score")
                for md in (r.get("metric_details") or [])
            }
            cells = []
            for n, _ in METRIC_ORDER:
                v = score_by_name.get(n)
                cells.append(f"{v:.2f}" if v is not None else "—")
            rows.append(
                f"| {r.get('test_id', '?')} | {r.get('status', '?')} "
                f"| {cells[0]} | {cells[1]} | {cells[2]} | {cells[3]} "
                f"| {cells[4]} | {cells[5]} | {cells[6]} |"
            )
        rows.append("")

    out_md.write_text("\n".join(rows), encoding="utf-8")

    # Print summary
    print(f"\n=== 7-Metric Avg Scores ({tier}) ===")
    header = f"{'Metric':<40} {'baseline':>10} {'partial':>10} {'full':>10}"
    print(header)
    print("-" * len(header))
    for name, group in METRIC_ORDER:
        cells = []
        for cfg in ("baseline", "partial", "full"):
            v = avgs.get(cfg, {}).get(name)
            cells.append(f"{v:.4f}" if v is not None else "—")
        print(f"{name:<40} {cells[0]:>10} {cells[1]:>10} {cells[2]:>10}")
    print(f"\nMarkdown report: {out_md}")
    return 0


if __name__ == "__main__":
    sys.exit(main())